config/routes.rb
Rails.application.routes.draw do
  


  resources :complaints

  resources :enterprises do
  	resources :complaints, only: [:create, :destroy]
  end

 

 
  devise_for :users, controllers: { registrations: 'users/registrations' }
  
  root 'enterprises#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/complaint.rb
class Complaint < ApplicationRecord
  belongs_to :user
  belongs_to :enterprise
end

app/models/enterprise.rb
class Enterprise < ApplicationRecord
	has_many: complaints
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
   before_action :authenticate_user!
end

app/controllers/complaints_controller.rb
class ComplaintsController < ApplicationController
  before_action :set_complaint, only: [:show, :edit, :update, :destroy]

  # GET /complaints
  # GET /complaints.json
  def index
    @complaints = Complaint.all
  end

  # GET /complaints/1
  # GET /complaints/1.json
  def show
  end

  # GET /complaints/new
  def new
    @complaint = Complaint.new
  end

  # GET /complaints/1/edit
  def edit
  end

  # POST /complaints
  # POST /complaints.json
 def create
    @enterprise = enterprise.find(params[:enterprise_id])
    @complaint.user_id = current_user.id
    @complaint = @enterprise.complaints.build(complaint_params)

    respond_to do |format|
      if @complaint.save
        format.html { redirect_to @enterprise, notice: 'Complaint was successfully created.' }
        format.json { render :show, status: :created, location: @enterprise }
        format.js
      else
        format.html { render :new }
        format.json { render json: @complaint.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /complaints/1
  # PATCH/PUT /complaints/1.json
  def update
    respond_to do |format|
      if @complaint.update(complaint_params)
        format.html { redirect_to @complaint, notice: 'Complaint was successfully updated.' }
        format.json { render :show, status: :ok, location: @complaint }
      else
        format.html { render :edit }
        format.json { render json: @complaint.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /complaints/1
  # DELETE /complaints/1.json
  def destroy
     @complaint.destroy
    respond_to do |format|
      format.html { redirect_to complaints_url, notice: 'Complaint was successfully destroyed.' }
      format.json { head :no_content }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_complaint
      @complaint = Complaint.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def complaint_params
      params.require(:complaint).permit(:content, :user_id, :enterprise_id)
    end
end

app/controllers/enterprises_controller.rb
class EnterprisesController < ApplicationController
  before_action :set_enterprise, only: [:show, :edit, :update, :destroy]

  # GET /enterprises
  # GET /enterprises.json
  def index
    @enterprises = Enterprise.all.reverse

    @enterprise = Enterprise.new
  end

  # GET /enterprises/1
  # GET /enterprises/1.json
  def show
    @complaint = @enterprise.complaints.build

    if params[:filter].present?
        @complaints = Complaint.where("user_id like ?", "%#{params[:filter]}%")
      else
        @complaints = @enterprise.complaints.reverse
      end 
  end


  # GET /enterprises/new
  def new
    @enterprise = Enterprise.new
  end

  # GET /enterprises/1/edit
  def edit
  end

  # POST /enterprises
  # POST /enterprises.json
  def create
    @enterprise = Enterprise.new(enterprise_params)

    respond_to do |format|
      if @enterprise.save
        format.html { redirect_to @enterprise, notice: 'Enterprise was successfully created.' }
        format.json { render :show, status: :created, location: @enterprise }
         format.js
      else
        format.html { render :new }
        format.json { render json: @enterprise.errors, status: :unprocessable_entity }
         format.js
      end
    end
  end

  # PATCH/PUT /enterprises/1
  # PATCH/PUT /enterprises/1.json
  def update
    respond_to do |format|
      if @enterprise.update(enterprise_params)
        format.html { redirect_to @enterprise, notice: 'Enterprise was successfully updated.' }
        format.json { render :show, status: :ok, location: @enterprise }
        format.js
      else
        format.html { render :edit }
        format.json { render json: @enterprise.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # DELETE /enterprises/1
  # DELETE /enterprises/1.json
  def destroy
    @enterprise.destroy
    respond_to do |format|
      format.html { redirect_to enterprises_url, notice: 'Enterprise was successfully destroyed.' }
      format.json { head :no_content }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enterprise
      @enterprise = Enterprise.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def enterprise_params
      params.require(:enterprise).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/complaints_helper.rb
module ComplaintsHelper
end

app/helpers/enterprises_helper.rb
module EnterprisesHelper
end

app/views/complaints/_form.html.erb
<%= form_with(model: complaint, local: true) do |form| %>
  <% if complaint.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(complaint.errors.count, "error") %> prohibited this complaint from being saved:</h2>

      <ul>
      <% complaint.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :complaint_content %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :complaint_user_id %>
  </div>

  <div class="field">
    <%= form.label :enterprise_id %>
    <%= form.text_field :enterprise_id, id: :complaint_enterprise_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/complaints/create.js.erb
$("tbody").prepend("<%= j render 'enterprises/complaints', complaint: @complaint %>");

app/views/complaints/edit.html.erb
<h1>Editing Complaint</h1>

<%= render 'form', complaint: @complaint %>

<%= link_to 'Show', @complaint %> |
<%= link_to 'Back', complaints_path %>

app/views/complaints/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Complaints</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th>Enterprise</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @complaints.each do |complaint| %>
      <tr>
        <td><%= complaint.content %></td>
        <td><%= complaint.user %></td>
        <td><%= complaint.enterprise %></td>
        <td><%= link_to 'Show', complaint %></td>
        <td><%= link_to 'Edit', edit_complaint_path(complaint) %></td>
        <td><%= link_to 'Destroy', complaint, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/complaints/new.html.erb
<h1>New Complaint</h1>

<%= render 'form', complaint: @complaint %>

<%= link_to 'Back', complaints_path %>

app/views/complaints/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @complaint.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @complaint.user %>
</p>

<p>
  <strong>Enterprise:</strong>
  <%= @complaint.enterprise %>
</p>

<%= link_to 'Edit', edit_complaint_path(@complaint) %> |
<%= link_to 'Back', complaints_path %>

app/views/enterprises/_complaints.html.erb
<tr>
	<td><%= complaint.content %></td>
	<td><%= complaint.user_id %></td>
</tr>

app/views/enterprises/_form.html.erb
<%= form_with(model: enterprise, local: true) do |form| %>
  <% if enterprise.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(enterprise.errors.count, "error") %> prohibited this enterprise from being saved:</h2>

      <ul>
      <% enterprise.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :enterprise_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/enterprises/create.js.erb
$("tbody").prepend("<%= j render 'enterprise', enterprise: @enterprise %>");

app/views/enterprises/destroy.js.erb
$("#enterprise_<%= @enterprise.id %>").toggle(400);

app/views/enterprises/edit.html.erb
<h1>Editing Enterprise</h1>

<%= render 'form', enterprise: @enterprise %>

<%= link_to 'Show', @enterprise %> |
<%= link_to 'Back', enterprises_path %>

app/views/enterprises/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Enterprises</h1>


<%= render 'form', enterprise: @enterprise %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @enterprises.each do |enterprise| %>
      <%= render 'enterprise', enterprise: enterprise %>
    <% end %>
  </tbody>
</table>

<br>

app/views/enterprises/new.html.erb
<h1>New Enterprise</h1>

<%= render 'form', enterprise: @enterprise %>

<%= link_to 'Back', enterprises_path %>

app/views/enterprises/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @enterprise.name %>
</p>

<%= form_for([@enterprise,@complaint], remote: true) do |f| %>
	<%= f.label :content, "quejas" %> <br>
	<%= f.text_area :content %> <br>
	<%= f.submit "Ingrese Nuevo Reclamo" %>
<% end %>
<br>
<h2>Reclamos Recientes</h2>
<input name="buscador">

<%= render 'complaints', complaint: @complaint %>

<table>
  <thead>
    <tr>
      <th>Contenido</th>
      <th>Usuario</th>
    </tr>
  </thead>

  <tbody>
    <% @complaints.each do |complaint| %>
      <%= render 'complaints', complaint: complaint %>
    <% end %>
  </tbody>
</table>

<script>
  $(document).ready(function(){
    $("[name='buscador']").on("input", function(){
      // console.log($(this).val());
        var filter = $(this).val();
        $.ajax({
          url: '<%= enterprises_path %>',
          type: 'GET',
          dataType: 'script',
          data: {filter: filter},
        })
      });
    });

</script>


<%= link_to 'Edit', edit_enterprise_path(@enterprise) %> |
<%= link_to 'Back', enterprises_path %>

app/views/enterprises/update.js.erb
$("#modal_enterprise_<%= @enterprise.id %>").modal('hide');
$("#enterprise_<%= @enterprise.id %>").empty();
$("tbody").prepend("<%= j render 'enterprise', enterprise: @enterprise %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PruebaFinal</title>
    <%= csrf_meta_tags %>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="navbar-header">
    <a class="navbar-brand" href="<%= root_path %>">Lista de Reclamos</a>
  </div>
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
    <% if user_signed_in? %>
      <li><a href="#%>">Mis Reclamos</a></li>
      <li><a href="#">Todos los reclamos</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      
        <li><a href="#">Hello <%= current_user.email%></a></li>
        <li><a href="<%= destroy_user_session_path %>" data-method='delete'>Log out</a></li>
      <% else %>
        <li><a href="<%= new_user_session_path %>">Log in</a></li>
        <li><a href="<%= new_user_registration_path %>">Sign up</a></li>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>